### ISSUE TITLE
Unseen, Important, Starred, Trash

### ISSUE THREAD

**Issue by hacky1997** [hacky1997/voice-based-email-for-blind#1]
Have to add more features like total number of deleted mails, flag a mail to important or starred, select particularly an unseen mail for read.

**Comment by adarsh-nl** [comment]
getting error
#project name
tts = gTTS(text="Project: Voice based Email for blind", lang='en')
ttsname=("vmail\vname.mp3")
tts.save(ttsname)



OSError:[Errno 22] Invalid argument: 'vmail\x0bname.mp3'

**Comment by hacky1997** [comment]
@adarsh-nl use a valid directory like -> C:/Users/sayak/Desktop 
Use your own proper directory.

**Comment by hacky1997** [comment]
@adarsh-nl If 'vmail\x0bname.mp3' occurs I mean its a unicode escape error. To solve this just use "C:\\Users\\[ur_directory]\\Desktop\\name.mp3"
r"C:\Users\[ur_directory]\Desktop\name.mp3"

**Comment by adarsh-nl** [comment]
[ur_directory] is the path that leads to the file present right

**Comment by adarsh-nl** [comment]
i installed all the required files via anaconda
i gave the path as you mentioned in the  eariler comment
the code compiles but the speech is not good its like gibberish

**Comment by hacky1997** [comment]
@adarsh-nl  Could you please tell me briefly? I know its sound a bit low and its for the tts module.

**Comment by adarsh-nl** [comment]
the audio is being repeated 
it doesn't stop

**Comment by hacky1997** [comment]
@adarsh-nl I have not used any loop for this. Ok, try to run this from command prompt.

**Comment by adarsh-nl** [comment]
i coded everything from the scratch
but i encounter  a error

SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials k16sm24937463pje.18 - gsmtp')

**Comment by hacky1997** [comment]
It is because of your gmail account. You have to select the trusted option of the Mailing protocol which i have used in code. I think you will get a mail into your inbox. Have you?

**Comment by adarsh-nl** [comment]
couldn't understand "trusted option of the mailing protocol"

**Comment by hacky1997** [comment]
https://www.google.com/settings/security/lesssecureapps
 Access for less security app enable karo

**Comment by exist-world** [comment]
Traceback (most recent call last):
  File "voice_based_email_for_blind.py", line 24, in <module>
    tts.save(ttsname)
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\site-packages\gtts\tts.py", line 248, in save
    with open(str(savefile), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/name.mp3'


for me its coming like this what can i do ?? Help me to solve out

**Comment by hacky1997** [comment]
@exist-world please create a new issue. This is @adarsh-nl 's issue.

**Comment by hacky1997** [comment]
@adarsh-nl have you sorted out your problem?

**Comment by adarsh-nl** [comment]
yes
