### ISSUE TITLE
Error in opening the audio file

### ISSUE THREAD

**Issue by exist-world** [hacky1997/voice-based-email-for-blind#5]
As you have mentioned in the document, I replaced the path of the mp3 file. But it is showing the following error:
Traceback (most recent call last):
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\media\codecs\wave.py", line 59, in __init__
    self._wave = wave.open(file)
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\wave.py", line 510, in open
    return Wave_read(f)
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\wave.py", line 164, in __init__
    self.initfp(f)
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\wave.py", line 131, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_based_email_for_blind.py", line 26, in <module>
    music = pyglet.media.load(ttsname, streaming = False)
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\media\__init__.py", line 143, in load
    raise first_exception
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\media\__init__.py", line 133, in load
    loaded_source = decoder.decode(file, filename, streaming)
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\media\codecs\wave.py", line 111, in decode
    return StaticSource(WaveSource(filename, file))
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\site-packages\pyglet\media\codecs\wave.py", line 61, in __init__
    raise WAVEDecodeException(e)
pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id

Please help me to solve this issue .

**Comment by hacky1997** [comment]
@exist-world It seems like you have an invalid or unsupported audio file. Recall that only FLAC, AIFF, and RIFF WAV files are supported.

If it's one of those, and it's still not working, please let me know. 
May I know your os?

Try this. Read the file with librosa, then convert it back to a temporary .wav file. Then read it back with the 'wave' package.
https://stackoverflow.com/questions/25672289/failed-to-open-file-file-wav-as-a-wav-due-to-file-does-not-start-with-riff-id/57349558#57349558

**Comment by exist-world** [comment]
thanks for ur suggestion i will try and tell
My os is windows 10

**Comment by exist-world** [comment]
Now  that audio file is working...but choosing option 1 gives me following error...

Traceback (most recent call last):
  File "voice_pro.py", line 107, in <module>
    mail.login('emailID','pswrd') #login part
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 730, in login
    raise last_exception
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "C:\Users\ELCOT\AppData\Local\Programs\Python\Python37\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials i17sm4151845pfr.67 - gsmtp')


And chosing option 2 gives me the following error

Traceback (most recent call last):
  File "voice_pro.py", line 89, in <module>
    if int(text) == 1:
ValueError: invalid literal for int() with base 10: 'Tu'

**Comment by hacky1997** [comment]
@exist-world bro, Here [mail.login('emailID','pswrd') #login part] You have to put your email id and password for login . After that if any error occurs then please tell me.

**Comment by exist-world** [comment]
yeah ..thank you !..Now 1 st option is working but in victim id i gave receiver mail id...it shows mail sent But receiver didnt get that mail
And giving 2 nd option shows me the following error
Traceback (most recent call last):
  File "voice_pro.py", line 89, in <module>
    if int(text) == 1:
ValueError: invalid literal for int() with base 10: 'Tu'

Help me to solve this one..!

**Comment by hacky1997** [comment]
@exist-world Its because of 'Tu' not '2'. I mean script recognise the 'Tu' not 2 and that's why it fetch the error.
Just edit it and add [ if int(text) == 2 or text == "tu": ] in the second if statement not the first one.

Now, I really don't know why u have not received the mail in inbox. Have you checked in spam folder? If not then use your primary email id in both as a sender and receiver email id.

**Comment by exist-world** [comment]
oh sry..I got mail in spam folder thank you...But for option 2 i already tried that again it shows the error

You said : Tu
Traceback (most recent call last):
  File "voice_pro.py", line 89, in <module>
    if int(text) == 1 or text == 'one':
ValueError: invalid literal for int() with base 10: 'Tu'

**Comment by hacky1997** [comment]
@exist-world I don't know why r getting all those mails in spam folder. May be some security checkings were going on and the last one I don't know why it take "Tu". When I used this project in my college program it was easily fetch and also no "Tu" problem. It take only "2". Okay just try to change it into 
text == 'Tu':
and if possible just remove the int() function form those two if statements.

**Comment by qsqqwqeqe** [comment]
ERROR: Could not find a version that satisfies the requirement avbin (from versions: none)
ERROR: No matching distribution found for avbin . Can u please tell about this problem brother.

**Comment by hacky1997** [comment]
@qsqqwqeqe please create a new issue. I will sort out there.

**Comment by hacky1997** [comment]
@exist-world Hey buddy! have you sorted out?

**Comment by exist-world** [comment]
No,if i remove int then it is coming like that
1. composed a mail.
2. Check your inbox
Your choice:
ok done!!
You said : 1

After that it was coming out...
And is that ok for giving all wave files as same like ""C:\\Users\\ELCOT\\Desktop\\alexa\\alexa\\fegormwx\\4.wav "   ?

**Comment by exist-world** [comment]
please Help me to solve this issue as soon as possible....project deadline is very short
In which IDE you run this one??
I simply tried in command prompt

**Comment by exist-world** [comment]
After i changed something,now its working but the problem is it seems like its reading encoded message...What to do ??

You said : Tu
Number of mails in your inbox :[b'6']
Number of UnSeen mails :('OK', [b'3 6'])
From: Google <no-reply@accounts.google.com>
Subject: Critical security alert
Body :--0000000000009cd67a059cb64e13
Content-Type: text/plain; charset="UTF-8"; format=flowed; delsp=yes
Content-Transfer-Encoding: base64

W2ltYWdlOiBHb29nbGVdDQpBY2Nlc3MgZm9yIGxlc3Mgc2VjdXJlIGFwcHMgc2V0dGluZyBoYXMg
YmVlbiB0dXJuZWQgb24NCg0KDQptaW5pMjBwcm8yMEBnbWFpbC5jb20NCkFjY2VzcyBmb3IgbGVz
cyBzZWN1cmUgYXBwcyBzZXR0aW5nIGhhcyBiZWVuIHR1cm5lZCBvbiBmb3IgeW91ciBHb29nbGUN
CkFjY291bnQgbWluaTIwcHJvMjBAZ21haWwuY29tLiBJZiB5b3UgZGlkbid0IGNoYW5nZSBpdCwg
eW91IHNob3VsZCBjaGVjaw0Kd2hhdCBoYXBwZW5lZC4NCkNoZWNrIGFjdGl2aXR5DQo8aHR0cHM6
Ly9hY2NvdW50cy5nb29nbGUuY29tL0FjY291bnRDaG9vc2VyP0VtYWlsPW1pbmkyMHBybzIwQGdt
YWlsLmNvbSZjb250aW51ZT1odHRwczovL215YWNjb3VudC5nb29nbGUuY29tL2FsZXJ0L250LzE1
Nzk2ODE3MDAwNjQ/cmZuJTNEMjglMjZyZm5jJTNEMSUyNmVpZCUzRC00MTY0NDc4Mzk5NjYwMDY5
MjY1JTI2ZXQlM0QwPg0KWW91IHJlY2VpdmVkIHRoaXMgZW1haWwgdG8gbGV0IHlvdSBrbm93IGFi
b3V0IGltcG9ydGFudCBjaGFuZ2VzIHRvIHlvdXINCkdvb2dsZSBBY2NvdW50IGFuZCBzZXJ2aWNl
cy4NCsKpIDIwMjAgR29vZ2xlIExMQywgMTYwMCBBbXBoaXRoZWF0cmUgUGFya3dheSwgTW91bnRh
aW4gVmlldywgQ0EgOTQwNDMsIFVTQQ0K
--0000000000009cd67a059cb64e13
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

.awl a {color: #FFFFFF; text-decoration: non=
e;} .abml a {color: #000000; font-family: Roboto-Medium,Helvetica,Arial,san=
s-serif; font-weight: bold; text-decoration: none;} .adgl a {color: rgba(0,=
 0, 0, 0.87); text-decoration: none;} .afal a {color: #b0b0b0; text-decorat=
ion: none;} @media screen and (min-width: 600px) {.v2sp {padding: 6px 30px =
0px;} .v2rsp {padding: 0px 10px;}} @media screen and (min-width: 600px) {.m=
dv2rw {padding: 40px 40px;}} Access for=
 less secure apps setting has been turned on=
mini20pro@gmail.comAccess for less secure apps setting has been turned on for your Google Acc=
ount mini20pro20@gmail.com. If you didn't change it, you should check what =
happened.Check activityYou rec=
eived this email to let you know about important changes to your Google Acc=
ount and services.© 2020 Google L=
LC, 1600 Amphitheatre Parkway, Mountain View=
, CA 94043, USA=

--0000000000009cd67a059cb64e13--

**Comment by hacky1997** [comment]
@exist-world I will update my project within two weeks. As this is 3 years old project so thats why it shows such  issues. May I know your project deadline ?

**Comment by hacky1997** [comment]
@exist-world https://support.google.com/mail/answer/7126229?p=BadCredentials&rd=2#cantsignin use this and then go to [https://support.google.com/accounts/answer/6010255] and then [If "Less secure app access" is off for your account] turn on.

**Comment by exist-world** [comment]
Project deadline is February last week..Thank u for ur kind help..

**Comment by exist-world** [comment]
yeah ! i turned it on and  mail gets received in spam folder....now its okay but during reading the message its reading some encoded value also...that is the problem

**Comment by hacky1997** [comment]
@exist-world If possible I will upload the latest one. I really don't understand the problem that why it goes to spam folder. Do you use any kind of mail tracking system or security addons?

**Comment by exist-world** [comment]
No i dont use any of that kind..its okay...but whenever i use  option 2 its seems like its checking for option 1 only...its shows folln error

You said : Tu
Traceback (most recent call last):
  File "voice_pro.py", line 90, in <module>
    if int(text)==1 or text == 'one':
ValueError: invalid literal for int() with base 10: 'Tu'

**Comment by hacky1997** [comment]
@exist-world Sorry for late response. Paste those with folln codes:

if text == '1' or text == 'One' or text == 'one':    

elif text == '2' or text == 'tu' or text == 'two' or text == 'Tu' or text == 'to' or text == 'To' :

Soon I will update the latest one. As I told you before it was almost 3 years old project.

**Comment by afuafu21** [comment]
Okay ..pls upload the latest one as soon as possible...Thanks in advance

**Comment by afuafu21** [comment]
i have one doubt...you gave mail id of the receiver as static in code...for getting dynamic input from the user for mail id how to use ?? Please help  quickly to solve this out..

**Comment by hacky1997** [comment]
@afuafu21 It arises some minor problem. I have added this feature in the latest one. But the problem is I have not enough time to test it. So, Its getting a bit late to upload. And there are another problem, if someone's email id is alphanumeric then the problem occurs, till now it should be in alphabet only.

**Comment by afuafu21** [comment]
Ohh Its okay...When u will upload the latest one.please upload soon or if u
don't mind send it to my mail...Because this month 18 is the last date for
my project submission and review....if u upload soon it is so helpful for
me....because of your contribution only i did this much in that project
Thanks a lot...

**Comment by hacky1997** [comment]
@afuafu21 Please provide your email id. I have not tested it yet.

**Comment by afuafu21** [comment]
Okay Thank you this is my mail id-mini20pro20@gmail.com

**Comment by swamy-m-s** [comment]
> @exist-world bro, Here [mail.login('emailID','pswrd') #login part] You have to put your email id and password for login . After that if any error occurs then please tell me.

Traceback (most recent call last):
  File "c:\Users\msswa\Desktop\Mini Project\voice-based-email-for-blind\voice_based_email_for_blind.py", line 104, in <module>
    mail.login('projectmini152@gmail.com','swamymsswamy') #login part
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\smtplib.py", line 730, in login
    raise last_exception
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h10sm5676812pfk.210 - gsmtp')

i am getting this error

**Comment by afuafu21** [comment]
@swamy-m-s 
Maybe this issue is coming because of some security issues . Google blocks sign-in attempts from apps which do not use  security standards. For this u have to check your mail settings and disable the 2 - step verification or authentication.

**Comment by swamy-m-s** [comment]
Tq I got that one it's working fine now tq

**Comment by hacky1997** [comment]
Issue has been resolved.
